services:
  1_4_add_field-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d

  1_4_krakend:
    image: devopsfaith/krakend:watch
    #image: krakend/krakend-ee:watch
    ports:
      - "8080:8080"
    volumes:
      - ./etc/krakend:/etc/krakend
    command: ["run", "-d", "-c", "krakend.json"]

volumes:
  db_data:
